<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
		<OutputType>Library</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AssemblyTitle>mycompany.package.datamodel</AssemblyTitle>
		<Product>mycompany.package.datamodel</Product>
		<Copyright>Copyright ©  2020</Copyright>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<IPlusIncludeDir>..\..\..\iPlus\bin\Debug\$(DefaultNetCoreTargetFramework)</IPlusIncludeDir>
		<OutputPath>$(SolutionDir)bin\$(Configuration)</OutputPath>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<IPlusIncludeDir>..\..\..\iPlus\bin\Release\$(DefaultNetCoreTargetFramework)</IPlusIncludeDir>
		<OutputPath>$(SolutionDir)bin\$(Configuration)</OutputPath>
	</PropertyGroup>
	<PropertyGroup>
		<EFCorePackageVersionFork Condition="'$(EFCorePackageVersionFork)' == ''">10.0.5</EFCorePackageVersionFork>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="mycompany.cs" />
		<Compile Remove="mycompany.Designer.cs" />
	</ItemGroup>
	<ItemGroup Condition="'$(EnableEFDesignTime)' != 'True'">
		<Compile Remove="CodeTemplates\T4TemplatePluralizer\MyPluralizer.cs" />
		<Compile Remove="CodeTemplates\T4TemplatePluralizer\MyDesignTimeServices.cs" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="gip.core.datamodel">
			<HintPath>$(IPlusIncludeDir)\gip.core.datamodel.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<Content Include="$(IPlusIncludeDir)\DbScripts\**\*.*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<Link>DbScripts\%(RecursiveDir)%(Filename)%(Extension)</Link>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<EntityDeploy Include="mycompany.edmx">
			<Generator>EntityModelCodeGenerator</Generator>
			<LastGenOutput>mycompany.Designer.cs</LastGenOutput>
		</EntityDeploy>
		<None Update="mycompany.edmx.diagram">
			<DependentUpon>mycompany.edmx</DependentUpon>
		</None>
	</ItemGroup>
	<ItemGroup>
		<Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="DbScripts\MyCompDB\dbsync_2020-05-01_01-01_developername.sql">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Content>
		<Content Include="DbScripts\MyCompDB\info.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<SubType>Designer</SubType>
		</Content>
	</ItemGroup>
	<ItemGroup Condition="'$(UseEFCoreForkIPlus)' == 'True'">
		<PackageReference Include="iPlus.EntityFrameworkCore" />
		<PackageReference Include="iPlus.EntityFrameworkCore.Abstractions" />
		<PackageReference Include="iPlus.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="iPlus.EntityFrameworkCore.Relational" />
		<PackageReference Include="iPlus.EntityFrameworkCore.Tools" >
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>
	<ItemGroup Condition="'$(UseEFCoreForkIPlus)' == 'True' and '$(EnableEFDesignTime)' == 'True'">
		<PackageReference Include="iPlus.EntityFrameworkCore.Design">
			<PrivateAssets>compile</PrivateAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup Condition="'$(UseEFCoreForkIPlus)' == 'False'">
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" >
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup Condition="'$(UseEFCoreForkIPlus)' == 'False' and '$(EnableEFDesignTime)' == 'True'">
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>compile</PrivateAssets>
		</PackageReference>
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
		<PackageReference Include="Microsoft.Data.SqlClient" />
		<PackageReference Include="System.Data.DataSetExtensions"/>
		<PackageReference Include="System.ComponentModel.Annotations" />
		<PackageReference Include="System.Configuration.ConfigurationManager" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="EFModels\" />
	</ItemGroup>
</Project>