// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using mycompany.package.datamodel;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ExampleV5Context), typeof(ExampleV5ContextModel))]
