// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace mycompany.package.datamodel
{
    public partial class ExampleV5ContextModel
    {
        private ExampleV5ContextModel()
            : base(skipDetectChanges: true, modelId: new Guid("19089ef0-2628-4be0-a74b-9bd00d22e2d5"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var inOrder = InOrderEntityType.Create(this);
            var inOrderPos = InOrderPosEntityType.Create(this);
            var material = MaterialEntityType.Create(this);

            InOrderPosEntityType.CreateForeignKey1(inOrderPos, inOrder);
            InOrderPosEntityType.CreateForeignKey2(inOrderPos, material);

            InOrderEntityType.CreateAnnotations(inOrder);
            InOrderPosEntityType.CreateAnnotations(inOrderPos);
            MaterialEntityType.CreateAnnotations(material);

            AddAnnotation("ProductVersion", "9.0.9");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
